---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: vault
spec:
  commonName: vault
  secretName: vault-tls
  duration: 336h     # 14 days
  renewBefore: 168h  #  7 days
  dnsNames:
    - vault.vault.svc.cluster.local
    - '{{repl list "vault" (ConfigOption "subdomain") | join "." }}'
    - vault
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: supply-chain-issuer
    kind: ClusterIssuer
    group: cert-manager.io
