apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: vault
spec:
  # namespace allows for a chart to be installed in an alternate namespace to
  # the default
  namespace: vault

  # chart identifies a matching chart from a .tgz
  chart:
    name: vault
    chartVersion: 0.23.0

  # helmVersion identifies the Helm Version used to render the chart. Default is v3.
  helmVersion: v3

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: true

  # weight determines the order that charts with "useHelmInstall: true" are applied, with lower weights first.
  weight: 30

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: 
    injector:
      enabled: false

    server:
      # affinity: ""
      # extraEnvironmentVars:
      #   VAULT_CACERT: /vault/userconfig/ca-certs/spire-ca.pem

      standalone:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
            tls_key_file  = "/vault/userconfig/vault-server-tls/tls.key"
            tls_client_ca_file = "/vault/userconfig/vault-server-tls/ca.crt"
            telemetry {
              unauthenticated_metrics_access = "true"
            }
          }
          storage "file" {
            path = "/vault/data"
          }

    # Vault is able to collect and publish various runtime metrics.
    # Enabling this feature requires setting adding `telemetry{}` stanza to
    # the Vault configuration. There are a few examples included in the `config` sections above.
    #
    # For more information see:
    # https://www.vaultproject.io/docs/configuration/telemetry
    # https://www.vaultproject.io/docs/internals/telemetry
    serverTelemetry:
      # Enable support for the Prometheus Operator. Currently, this chart does not support
      # authenticating to Vault's metrics endpoint, so the following `telemetry{}` must be included
      # in the `listener "tcp"{}` stanza
      #  telemetry {
      #    unauthenticated_metrics_access = "true"
      #  }
      #
      # See the `standalone.config` for a more complete example of this.
      #
      # In addition, a top level `telemetry{}` stanza must also be included in the Vault configuration:
      #
      # example:
      #  telemetry {
      #    prometheus_retention_time = "30s",
      #    disable_hostname = true
      #  }
      #
      # Configuration for monitoring the Vault server.
      serviceMonitor:
        # The Prometheus operator *must* be installed before enabling this feature,
        # if not the chart will fail to install due to missing CustomResourceDefinitions
        # provided by the operator.
        #
        # Instructions on how to install the Helm chart can be found here:
        #  https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
        # More information can be found here:
        #  https://github.com/prometheus-operator/prometheus-operator
        #  https://github.com/prometheus-operator/kube-prometheus

        # Enable deployment of the Vault Server ServiceMonitor CustomResource.
        enabled: true

        # Selector labels to add to the ServiceMonitor.
        # When empty, defaults to:
        #  release: prometheus
        selectors: {}

        # Interval at which Prometheus scrapes metrics
        interval: 30s

        # Timeout for Prometheus scrapes
        scrapeTimeout: 10s
      
    volumes:
    - name: ca-certs
      configMap:
        name: spire-ca-certs
    - name: vault-tls
      secrets:
        name: vault-tls

    volumeMounts:
    - name: ca-certs
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: spire-ca.pem
      readOnly: true
    - name: vault-tls
      mountPath: /vault/userconfig/vault-server-tls
      readOnly: true
