---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-certificate-bundle
spec:
  template:
    spec:
     containers:
      - image: vault
        name: 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
        - /bin/sh
        - -c
        - |
      volumes:
      - name: vault-tls
        secret:
          defaultMode: 420
          secretName: vault-tls
      volumeMounts:
      - name: vault-tls
        mountPath: /vault/userconfig/vault-server-tls
        readOnly: true
      restartPolicy: Never
