---
apiVersion: batch/v1
kind: Job
metadata:
  name: unseal-vault
  namespace: vault
spec:
  template:
    spec:
      containers:
      - image: vault
        name: unseal
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
        - /bin/sh
        - -c
        - |
          export VAULT_ADDR=https://vault-internal:8200 
          export VAULT_CACERT=/vault/userconfig/vault-server-tls/ca.crt 
 
          # wait for vault to start, the status command may error
          set +o pipefail
          while ! vault status 2>&1 | grep -q "^Initialized"; do
            sleep 5
          done
 
          if vault status 2>&1 | grep -q '^Initialized.*false'; then
            INIT_OUT=$(vault operator init --key-shares 1 --key-threshold 1)
            UNSEAL_KEY=$(echo "$INIT_OUT" | grep "Unseal Key" | sed 's/^.*: //')
          fi

          # this is not ideal, but a good stopgap while developing
          echo "$INIT_OUT"
 
          if vault status 2>&1 | grep -q '^Sealed.*true'; then
            vault operator unseal "$UNSEAL_KEY"
          fi 
          cat 
        volumeMounts:
        - name: vault-tls
          mountPath: /vault/userconfig/vault-server-tls
          readOnly: true
      volumes:
      - name: vault-tls
        secret:
          defaultMode: 420
          secretName: vault-tls
      restartPolicy: Never
