apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: moxie
spec:
  descriptor:
    links:
    - description: "Vault Secret Store"
      url: 'https://vault.{{repl ConfigOption "subdomain"}}'
