apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight-checks
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.23.0" 
              message: Moxie requires a supported version of Kubernetes
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.25.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.25.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - containerRuntime:
        outcomes:
          - pass:
              when: "== containerd"
              message: containerd container runtime was found.
          - fail:
              message: Did not find containerd container runtime.
