---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: moxie
spec:
  title: moxie
  icon: https://raw.githubusercontent.com/ossf/artwork/master/openssf/icon/color/openssf-icon-color.png
  additionalNamespaces:
  - spire
  statusInformers: 
  - cert-manager/deployment/cert-manager
  - spire/statefulset/spire-server
  ports: []
