---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spire-oidc
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: "spire-oidc.spire.svc.cluster.local"
      http:
        paths:
          - path: /.well-known/openid-configuration
            pathType: Prefix
            backend:
              service:
                name: release-name-spire-oidc
                port:
                  number: 443               
          - path: /keys
            pathType: Prefix
            backend:
              service:
                name: release-name-spire-oidc
                port:
                  number: 443
    - host: '{{repl list "oidc" (ConfigOption "subdomain") | join "." }}'
      http:
        paths:
          - path: /.well-known/openid-configuration
            pathType: Prefix
            backend:
              service:
                name: release-name-spire-oidc
                port:
                  number: 443               
          - path: /keys
            pathType: Prefix
            backend:
              service:
                name: release-name-spire-oidc
                port:
                  number: 443
