---
apiVersion: v1
kind: Secret
metadata:
  name: supply-chain-ca
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "certificate_chain" "generate" }}'
type: kubernetes.io/tls
data:
  tls.crt: '{{repl ConfigOptionData "signing_certificate" }}'
  tls.key: '{{repl ConfigOptionData "signing_key" }}'
  ca.crt: '{{repl ternary (ConfigOptionData "root_certificate") (ConfigOptionData "signing_certificate") ( ConfigOption "root_certificate" | empty ) }}'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "certificate_chain" "provide" }}'
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: supply-chain-ca
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "certificate_chain" "provide" }}'
spec:
  isCA: true
  commonName: supply-chain-ca
  secretName: supply-chain-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: supply-chain-issuer
spec:
  ca:
    secretName: supply-chain-ca
